spring:
  profiles:
    include:
      - database
      - discord
      - redis
      - email
      - jwt
  data:
    redis:
      repositories:
        enabled: false

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: false
        generate_ddl: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
    database: mysql