spring:
  datasource:
    url: jdbc:mysql://nalance-db.c56yu8oqutoa.ap-northeast-2.rds.amazonaws.com:3306/nalance-db
    username: nalance_master
    password: Nalance2025!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
    database: mysql

  cloud:
    aws:
      credentials:
        access-key: YOUR_AWS_ACCESS_KEY
        secret-key: YOUR_AWS_SECRET_KEY
      s3:
        bucket: YOUR_BUCKET_NAME
      region:
        static: YOUR_REGION